- name: Ensure fonts directory
  file:
    path: "{{ ansible_env.HOME }}/.fonts"
    state: directory
- name: MesloLGS exists
  shell: "ls {{ ansible_env.HOME }}/.fonts/MesloLGS*NF*.ttf"
  register: meslo_exists
  ignore_errors: true
- name: Download MesloLGS
  when: meslo_exists is failed
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.fonts/"
    force: true
  with_items: "{{ meslo_fonts }}"
- name: Copy MesloLGS
  #when: meslo_exists is failed
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.fonts/{{ item }}"
    dest: /usr/local/share/fonts
    remote_src: true
  with_items: "{{ meslo_fonts }}"
- name: Update font cache
  #when: meslo_exists is failed
  ansible.builtin.command: fc-cache -f -v