---

- hosts: all
  gather_facts: true
  become: false
  user: rash
  tasks:
  - block: # Install initial packages
    - name: Installing basic packages
      become: true
      apt:
        name:
          - git
          - curl
          - wget
        state: latest
        update_cache: true
